### ISSUE TITLE
Black Screen after 30 Seconds into installation

### ISSUE THREAD

**Issue by PhilippKath** [willza3/macOS-strix-B450i#10]
I am running into this issue but the fix does not work for me: https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/troubleshooting.html#frozen-in-the-macos-installer-after-30-seconds

This repository is using AMDRyzenCPUPowerManagement.kext instead of NullCPUPowerManagement.kext so i tried to remove it and use DummyPowerManagement instead but it didn't work.

**Comment by PhilippKath** [comment]
Specs:
* Motherboard: ASUS ROG Strix B450-
* CPU: AMD Ryzen 5 3800X
* GPU: Sapphire Nitro+ 5700 XT

**Comment by willza3** [comment]
I've noticed you're using a Navi GPU, have you included `agdpmod=pikera` in your boot arguments? Also keep in mind DisplayPort can be a hit or miss as WhateverGreen needs to be adapted. 

I'm not sure this issue is caused by anything power management related as:

- `NullCPUPowerManagement.kext` was replaced by `DummyPowerManagement` in newer versions of OC, it is already enabled in this configuration by default. 

- `AMDRyzenCPUPowerManagement.kext` isn't essential and macOS will boot without it.

You may need to update your BIOS as this has helped resolve other issues, I've also updated the recommended settings to use in the readme 🙂
