### ISSUE TITLE
Rear Mic In Doesn't Work

### ISSUE THREAD

**Issue by EfraimLA** [willza3/macOS-strix-B450i#9]
As the title says

**Comment by willza3** [comment]
Unfortunately this is because AppleALC doesn't really support line in mics on Ryzen/TR CPUs.

[VoodooHDA](https://sourceforge.net/projects/voodoohda/) will have better support for a line in mic but at the cost of poorer audio quality compared to AppleALC. I don't have a line in mic so I can't test if it works... however if you wanted to stick with AppleALC, my HyperX USB adapter works perfectly fine!

(Edit: Ignore this advice and check my next reply)

![Screenshot 2020-05-02 at 22 12 58](https://user-images.githubusercontent.com/41086361/80892446-17428180-8cc2-11ea-8391-0293611339b2.png)

**Comment by EfraimLA** [comment]
So nothing else to try? Well some mics works, how to know?

**Comment by willza3** [comment]
You could try with a 3.5mm to USB adapter? I can't test anything as I only have a USB mic.

**Comment by willza3** [comment]
I've had a look into this and the best/most stable option would be to buy a USB DAC/Adapter for your microphone. Personally I'm using the HyperX adapter that came with my headphones and I've had no issues using my mic in apps like Discord, Teams and Telegram.

Sadly there aern't really any other patches that have been developed for mic input for AMD, you can always try VoodooHDA however it's known to cause stability issues and has worse audio quality compared to AppleALC.

**Comment by EfraimLA** [comment]
I prefer use some adapter due VoodooHDA issues and quality, thanks and hope we've a patch for it
